// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using RarePuppers.Data;
using System;

namespace RarePuppers.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180730010740_updated")]
    partial class updated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("RarePuppers.Data.Attribute", b =>
                {
                    b.Property<int>("attribute_id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("attribute_type_id");

                    b.Property<string>("image_src");

                    b.Property<string>("name");

                    b.Property<decimal>("rarity");

                    b.HasKey("attribute_id");

                    b.HasIndex("attribute_type_id");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("RarePuppers.Data.AttributeType", b =>
                {
                    b.Property<int>("attribute_type_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("attribute_type_id");

                    b.ToTable("AttributeTypes");
                });

            modelBuilder.Entity("RarePuppers.Data.Home", b =>
                {
                    b.Property<int>("home_id");

                    b.Property<int>("user_id");

                    b.Property<int>("home_type_id");

                    b.Property<string>("name");

                    b.HasKey("home_id", "user_id");

                    b.HasIndex("home_type_id");

                    b.HasIndex("user_id");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("RarePuppers.Data.HomeType", b =>
                {
                    b.Property<int>("home_type_id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("capacity");

                    b.Property<string>("home_image_src");

                    b.Property<string>("name");

                    b.HasKey("home_type_id");

                    b.ToTable("HomeTypes");
                });

            modelBuilder.Entity("RarePuppers.Data.Pupper", b =>
                {
                    b.Property<int>("pupper_id");

                    b.Property<int>("user_id");

                    b.Property<int>("color");

                    b.Property<int>("ears");

                    b.Property<int>("eyes");

                    b.Property<int>("tail");

                    b.HasKey("pupper_id", "user_id");

                    b.HasIndex("user_id");

                    b.ToTable("Puppers");
                });

            modelBuilder.Entity("RarePuppers.Data.Role", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("role_name");

                    b.HasKey("role_id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RarePuppers.Data.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("hashedPassword");

                    b.Property<int>("role_id");

                    b.Property<string>("username");

                    b.HasKey("user_id");

                    b.HasIndex("role_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RarePuppers.Data.Attribute", b =>
                {
                    b.HasOne("RarePuppers.Data.AttributeType", "attribute")
                        .WithMany("attributes")
                        .HasForeignKey("attribute_type_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RarePuppers.Data.Home", b =>
                {
                    b.HasOne("RarePuppers.Data.HomeType", "HomeType")
                        .WithMany("homes")
                        .HasForeignKey("home_type_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RarePuppers.Data.User", "User")
                        .WithMany("homes")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RarePuppers.Data.Pupper", b =>
                {
                    b.HasOne("RarePuppers.Data.User", "User")
                        .WithMany("puppers")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RarePuppers.Data.User", b =>
                {
                    b.HasOne("RarePuppers.Data.Role", "role")
                        .WithMany("Users")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
